// Apex — preload script. Exposes a safe, typed-ish API to the renderer.

const { contextBridge, ipcRenderer } = require("electron");

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);
// Subscribe to main-process events; returns an unsubscribe fn.
const on = (channel, handler) => {
  const wrapped = (_e, payload) => handler(payload);
  ipcRenderer.on(channel, wrapped);
  return () => ipcRenderer.removeListener(channel, wrapped);
};

contextBridge.exposeInMainWorld("apex", {
  settings: {
    get: (key) => invoke("settings:get", key),
    set: (key, value) => invoke("settings:set", key, value),
    all: () => invoke("settings:all"),
    pickDirectory: () => invoke("dialog:pickDirectory"),
    pickFile: (filters) => invoke("dialog:pickFile", filters),
  },
  tasks: {
    list: (filter) => invoke("tasks:list", filter),
    create: (t) => invoke("tasks:create", t),
    update: (id, patch) => invoke("tasks:update", id, patch),
    delete: (id) => invoke("tasks:delete", id),
    toggle: (id) => invoke("tasks:toggle", id),
    habitStreak: (id) => invoke("tasks:habitStreak", id),
    habitStreaksFor: (ids) => invoke("tasks:habitStreaksFor", ids),
    today: () => invoke("tasks:today"),
    upcoming: (days) => invoke("tasks:upcoming", days),
    completedOn: (d) => invoke("tasks:completedOn", d),
  },
  checkins: {
    today: () => invoke("checkins:today"),
    upsert: (p) => invoke("checkins:upsert", p),
    last: (days) => invoke("checkins:last", days),
  },
  dayNotes: {
    get: (date) => invoke("dayNotes:get", date),
    upsert: (p) => invoke("dayNotes:upsert", p),
    list: (limit) => invoke("dayNotes:list", limit),
    delete: (date) => invoke("dayNotes:delete", date),
    summarize: (p) => invoke("dayNotes:summarize", p),
    hasPasscode: () => invoke("dayNotes:hasPasscode"),
    setPasscode: (passcode) => invoke("dayNotes:setPasscode", { passcode }),
    unlock: (passcode) => invoke("dayNotes:unlock", { passcode }),
    lock: () => invoke("dayNotes:lock"),
    isUnlocked: () => invoke("dayNotes:isUnlocked"),
    clearPasscode: (passcode) => invoke("dayNotes:clearPasscode", { passcode }),
    resetPasscode: () => invoke("dayNotes:resetPasscode", { confirm: "DELETE" }),
  },
  streak: {
    status: () => invoke("streak:status"),
  },
  goals: {
    list: () => invoke("goals:list"),
    upsert: (g) => invoke("goals:upsert", g),
    delete: (id) => invoke("goals:delete", id),
    incrementProgress: (id, by) => invoke("goals:incrementProgress", id, by),
    resetWeek: () => invoke("goals:resetWeek"),
  },
  schedule: {
    today: () => invoke("schedule:today"),
    upcoming: (days) => invoke("schedule:upcoming", days),
    list: () => invoke("schedule:list"),
    forDayOrder: (d) => invoke("schedule:forDayOrder", d),
    upsert: (row) => invoke("schedule:upsert", row),
    delete: (id) => invoke("schedule:delete", id),
    replaceAll: (rows) => invoke("schedule:replaceAll", rows),
    resyncFromAcademia: (folder) => invoke("schedule:resyncFromAcademia", folder),
    parseJson: (p) => invoke("schedule:parseJson", p),
    setDayOrderForDate: (iso, d) => invoke("schedule:setDayOrderForDate", iso, d),
    pickImages: () => invoke("schedule:pickImages"),
    parseImages: (payload) => invoke("schedule:parseImages", payload),
    importImageRows: (rows) => invoke("schedule:importImageRows", rows),
    overridesForDate: (iso) => invoke("schedule:overridesForDate", iso),
    setOverride: (iso, classId, patch) => invoke("schedule:setOverride", iso, classId, patch),
    addExtraClass: (iso, payload) => invoke("schedule:addExtraClass", iso, payload),
    clearOverride: (iso, classId) => invoke("schedule:clearOverride", iso, classId),
    deleteOverrideById: (id) => invoke("schedule:deleteOverrideById", id),
  },
  timer: {
    active: () => invoke("timer:active"),
    start: (p) => invoke("timer:start", p),
    extend: (mins) => invoke("timer:extend", mins),
    stop: () => invoke("timer:stop"),
    cancel: () => invoke("timer:cancel"),
    onUpdate: (h) => on("timer:update", h),
  },
  srm: {
    saveCreds: (creds) => invoke("srm:saveCreds", creds),
    clearCreds: () => invoke("srm:clearCreds"),
    hasCreds: () => invoke("srm:hasCreds"),
    syncNow: (opts) => invoke("srm:syncNow", opts),
    openLoginWindow: () => invoke("srm:openLoginWindow"),
    logout: () => invoke("srm:logout"),
    diagnose: () => invoke("srm:diagnose"),
  },
  notifier: {
    status: () => invoke("notifier:status"),
    setEnabled: (on) => invoke("notifier:setEnabled", on),
    setLeads: (opts) => invoke("notifier:setLeads", opts),
    test: () => invoke("notifier:test"),
    onNavGoto: (h) => on("nav:goto", h),
  },
  shortcuts: {
    onQuickCapture: (h) => on("quick-capture:open", h),
  },
  // kept for backwards-compat; UI should use schedule.*
  timetable: {
    load: (folder) => invoke("timetable:load", folder),
    today: () => invoke("timetable:today"),
  },
  ollama: {
    listModels: () => invoke("ollama:listModels"),
    plan: (ctx) => invoke("ollama:plan", ctx),
    chat: (p) => invoke("ollama:chat", p),
    burnoutSuggest: (ctx) => invoke("ollama:burnoutSuggest", ctx),
    recommend: (opts) => invoke("ollama:recommend", opts),
    burnoutCheck: (ctx) => invoke("ollama:burnoutCheck", ctx),
    eveningReview: (ctx) => invoke("ollama:eveningReview", ctx),
    best: () => invoke("ollama:best"),
    start: () => invoke("ollama:start"),
    ping: () => invoke("ollama:ping"),
  },
  burnout: {
    latestReport: () => invoke("burnout:latestReport"),
    recent: (days) => invoke("burnout:recent", days || 7),
  },
  github: {
    fetchUser: (u) => invoke("github:fetchUser", u),
    fetchRepos: (u) => invoke("github:fetchRepos", u),
    fetchLanguages: (fn) => invoke("github:fetchLanguages", fn),
    rateLimit: () => invoke("github:rateLimit"),
  },
  people: {
    list: (f) => invoke("people:list", f),
    upsert: (p) => invoke("people:upsert", p),
    delete: (id) => invoke("people:delete", id),
    repos: (id) => invoke("people:repos", id),
    sync: (id) => invoke("people:sync", id),
    syncAll: () => invoke("people:syncAll"),
    onSyncProgress: (h) => on("people:syncProgress", h),
    heatStrips: (ids, days) => invoke("people:heatStrips", ids, days),
  },
  cp: {
    fetchPerson: (id) => invoke("cp:fetchPerson", id),
    fetchAll: () => invoke("cp:fetchAll"),
    stats: (id) => invoke("cp:stats", id),
    submissions: (id, limit) => invoke("cp:submissions", id, limit),
    self: () => invoke("cp:self"),
    selfCached: () => invoke("cp:selfCached"),
    leaderboard: (platform) => invoke("cp:leaderboard", platform),
    summarize: (args) => invoke("cp:summarize", args),
    onProgress: (h) => on("cp:progress", h),
  },
  ntl: {
    scrape: (lab) => invoke("ntl:scrape", lab),
    scrapeAll: () => invoke("ntl:scrapeAll"),
    import: (members) => invoke("ntl:import", members),
  },
  interests: {
    list: () => invoke("interests:list"),
    upsert: (i) => invoke("interests:upsert", i),
    delete: (id) => invoke("interests:delete", id),
  },
  backup: {
    export: () => invoke("backup:export"),
    import: () => invoke("backup:import"),
    info: () => invoke("backup:info"),
  },
  activity: {
    add: (e) => invoke("activity:add", e),
    list: (opts) => invoke("activity:list", opts),
    delete: (id) => invoke("activity:delete", id),
    todayTotals: () => invoke("activity:todayTotals"),
    weekTotals: () => invoke("activity:weekTotals"),
    recentPushes: (opts) => invoke("activity:recentPushes", opts),
    totalsOn: (d) => invoke("activity:totalsOn", d),
    trend: (days) => invoke("activity:trend", days),
    topApps: (d, limit) => invoke("activity:topApps", d, limit),
    feed: (opts) => invoke("activity:feed", opts),
  },
  tracker: {
    start: () => invoke("tracker:start"),
    stop: () => invoke("tracker:stop"),
    status: () => invoke("tracker:status"),
    categorize: (app, category) => invoke("tracker:categorize", app, category),
    onNudge: (h) => on("activity:nudge", h),
    onSessionEnded: (h) => on("activity:sessionEnded", h),
  },
  wellbeing: {
    devices: () => invoke("wellbeing:devices"),
    syncNow: () => invoke("wellbeing:syncNow"),
  },
  battery: {
    supported: () => invoke("battery:supported"),
    run: (duration) => invoke("battery:run", duration),
    latest: () => invoke("battery:latest"),
    syncToActivity: (duration) => invoke("battery:syncToActivity", duration),
  },
  calendar: {
    parse: (p) => invoke("calendar:parse", p),
    sync: (p) => invoke("calendar:sync", p),
    list: (limit) => invoke("calendar:list", limit),
  },
  import: {
    preview: (url) => invoke("import:preview", url),
    previewNtl4: () => invoke("import:previewNtl4"),
    commit: (list) => invoke("import:commit", list),
  },
  repo: {
    detail: (repoId) => invoke("repo:detail", repoId),
    summarize: (args) => invoke("repo:summarize", args),
    listByPerson: (personId) => invoke("repo:listByPerson", personId),
    recentCommits: (args) => invoke("repo:recentCommits", args),
    summarizeRecentChanges: (args) => invoke("repo:summarizeRecentChanges", args),
    chat: (args) => invoke("repo:chat", args),
  },
  commit: {
    detail: (args) => invoke("commit:detail", args),
    chat: (args) => invoke("commit:chat", args),
  },
  ext: {
    open: (url) => invoke("ext:open", url),
    openSpotify: () => invoke("ext:openSpotify"),
  },
});
